FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.0

ENV xpack.security.enabled true
ENV xpack.watcher.enabled true
ENV xpack.graph.enabled true
ENV xpack.monitoring.enabled true
ENV http.host 0.0.0.0
ENV transport.host 127.0.0.1